INTYGFV-15763: Updated logging for SRS
sklintyg/frontend pull request #1020
Opened 2023-07-04 14:31 UTC by mhornfeldt

2023-07-05 08:54 UTC, SamuelTilly submitted a review, later dismissed

2023-08-02 05:15 UTC, mww-sopra-steria requested changes
Looks great! Could you add some tests to the new component and middleware behaviours?

2023-08-16 08:20 UTC, ChrilleSigerhed reviewed
Great job! I Like how you solved the issue with controlling if the SrsPanel is active!

Should we add the new feature launchFromOrigin when the user opens the certificate from rs and open the SrsPanel when that happends?

2023-08-16 08:29 UTC, mhornfeldt commented
> Great job! I Like how you solved the issue with controlling if the SrsPanel is active!
> 
> Should we add the new feature launchFromOrigin when the user opens the certificate from rs and open the SrsPanel when that happends?

I've added a new jira for this.

2023-08-16 08:30 UTC, ChrilleSigerhed approved these changes

2023-08-16 08:32 UTC, merged