K1J-632: Added banner for inactive certificate types.
sklintyg/frontend pull request #1445
Opened 2024-12-18 15:39 UTC by ChrilleSigerhed

2024-12-18 15:58 UTC, ChrilleSigerhed commented
![image](https://github.com/user-attachments/assets/d1b3676c-cde1-4de1-9383-b24a33572c36)

2024-12-19 06:07 UTC, mww-sopra-steria requested changes
See comment. It will remove the risk of it displaying multiple notifications. The certificate could be of a version that is not the latest major of the type and it could happen that the type has been inactivated.

2024-12-19 06:07 UTC, mww-sopra-steria commented on apps/webcert/src/page/CertificatePage.tsx
> +            <InactiveCertificateTypeNotification />
The comment is not on the correct line, but I add it here as MajorVersionNotification is added here.

Could we add logic to MajorVersionNotification that it is only displayed if inactiveCertificateType not true?

2024-12-19 07:53 UTC, mww-sopra-steria approved these changes
Nice!

2024-12-19 07:54 UTC, merged