INTYGFV-14235: Added validation for diagnosis component
sklintyg/frontend pull request #251
Opened 2021-12-15 13:11 UTC by mhornfeldt

2021-12-16 13:02 UTC, mww-sopra-steria requested changes
The logic is not trivial and not absolutely clear by reading the code. 

Is it possible to add some tests to verify some of the intricate logic? Anyone that has to change this component will be scared to brake something :-)

2021-12-16 14:21 UTC, mhornfeldt commented on packages/webcert/src/feature/certificate/Inputs/UeDiagnoses.tsx
>    //TODO: Validering under varje input
The code related to showing the error messages I can try to write tests for. However, a lot of the added logic is related to styling of the components. Should I also write tests for that?

2021-12-20 13:07 UTC, mhornfeldt commented on packages/webcert/src/feature/certificate/Inputs/UeDiagnoses.tsx
>    //TODO: Validering under varje input
@mww-sopra-steria Did you have time to look at my question?

2021-12-29 13:09 UTC, mww-sopra-steria approved these changes

2021-12-29 13:28 UTC, merged