INTYGFV-14430: Changed font size to be smaller and fixed mandatory ic…
sklintyg/frontend pull request #309
Opened 2022-02-15 08:46 UTC by mhornfeldt

…on placement

2022-02-15 10:01 UTC, perfli commented
Is there a reason as to why we diverge from the style guide regarding default font size for webcert? From my perspective that goes against the purpose of a style guide.

2022-02-17 09:14 UTC, mhornfeldt commented
> Is there a reason as to why we diverge from the style guide regarding default font size for webcert? From my perspective that goes against the purpose of a style guide.

You can read more in the Jira but to summarize, test believes that the application would benefit from smaller text. The style guide is mainly developed for websites with less content and information on one single page than WC. We have suggested to the developers of the style guide a setting where components, and in this case text, could have configurable sizes. This has not been implemented yet so we have overrided some elements in the style guide. This change would override the text, previous changes have for example made input fields and buttons smaller.

2022-02-18 13:43 UTC, perfli requested changes

2022-02-18 13:48 UTC, mhornfeldt commented on packages/webcert/src/components/header/WebcertHeaderUnit.tsx
> -  font-size: 13px;
With the change of inactive unit the caregiver name had gotten a smaller font-size than the doctor name but they should be the same size. If the inactive unit text should be smaller then I can add that seperately and not on the wrapper.

2022-02-18 13:50 UTC, perfli commented on packages/webcert/src/components/header/WebcertHeaderUnit.tsx
> -  font-size: 13px;
I see. As long as the inactive unit text is 13px then it's fine.

2022-02-18 13:55 UTC, mhornfeldt commented on packages/webcert/src/components/header/WebcertHeaderUnit.tsx
> -  font-size: 13px;
I will change it to 12px so it matches the doctor role and unit name like before.

2022-02-18 13:56 UTC, mhornfeldt commented on packages/common/src/components/utils/Accordion.tsx
> +          <MandatoryIcon additionalStyles={mandatoryIconAdditionalStyles} display={displayMandatory as boolean} />{' '}
We can utilize this moving forward.

2022-02-18 14:30 UTC, perfli approved these changes

2022-02-18 14:49 UTC, merged