INTYGFV-14460: Added possibility to search for patient
sklintyg/frontend pull request #325
Opened 2022-03-11 14:58 UTC by mhornfeldt

2022-03-16 13:58 UTC, perfli requested changes

2022-03-17 07:22 UTC, mhornfeldt commented on packages/webcert/src/components/header/WebcertHeader.tsx
> +const WebcertHeader: React.FC<Props> = ({ isEmpty = false }) => {
The other header components have Webcert before so I was following the same pattern

2022-03-17 07:24 UTC, mhornfeldt commented on packages/webcert/src/components/patient/PatientSearch.test.tsx
> +    it('should allow user to type patient id', () => {
No it tests the connection between user input and value for component. The textinput has logic deciding the value and it doesn't just set the input as its value.

2022-03-17 07:25 UTC, mhornfeldt commented on packages/webcert/src/page/CreateCertificatePage.tsx
> +  }, [history, dispatch, patientId])
This was suggested from IntelliJ. It gives a warning if I don't add it.

2022-03-17 07:27 UTC, mhornfeldt commented on packages/webcert/src/App.tsx
> +          path={'/create/:patientId?'}
This is how it has been before. Search/create will be accessible from the same tab later so I think it makes sense to have them in the same route.

2022-03-17 07:28 UTC, mhornfeldt commented on packages/webcert/src/store/uiReducers.ts
>    uiCertificate: certificateReducer,
This is how we have done it from the beginning. For new states we should follow the old pattern.

2022-03-17 07:44 UTC, mhornfeldt commented on packages/webcert/src/App.tsx
> +            <ErrorBoundary fallbackRender={({ error }) => <>Ett fel har inträffat: {error.message}</>} onError={onError}>
I don't know I was following the pattern from before. If we put it one level up then the errorpage will have it too.

2022-03-17 07:51 UTC, perfli commented on packages/webcert/src/App.tsx
> +            <ErrorBoundary fallbackRender={({ error }) => <>Ett fel har inträffat: {error.message}</>} onError={onError}>
I don't think that would be a bad thing, even if `ErrorPage` never generates an unhandled error.

2022-03-17 09:39 UTC, mhornfeldt commented on packages/webcert/src/App.tsx
> +            <ErrorBoundary fallbackRender={({ error }) => <>Ett fel har inträffat: {error.message}</>} onError={onError}>
Okay I've moved it now

2022-03-18 13:28 UTC, HelenaEdblad approved these changes

2022-03-18 13:33 UTC, merged