INTYGFV-14465: List for signed certificates
sklintyg/frontend pull request #343
Opened 2022-04-22 14:55 UTC by mhornfeldt

2022-04-22 14:55 UTC, mhornfeldt commented
Not ready for review

2022-04-25 12:35 UTC, perfli requested changes
Is it just me or does this PR also include the fixes you merged to master earlier?

2022-04-25 12:35 UTC, perfli commented on packages/webcert/src/page/ListPage.tsx
> +      return nbrOfDraftsOnUnit === 0 && false
Left behind test?

2022-04-26 06:28 UTC, mhornfeldt commented on packages/webcert/src/feature/list/listUtils.tsx
> +  let isDefault = true
Yes it's intentional since the default state is that the value is default

2022-04-26 06:45 UTC, mhornfeldt commented on packages/webcert/src/feature/list/filter/DateRangeFilter.tsx
> +    } else if (from && to && !isDateRangeValidOrIncomplete(from, to)) {
No because that's a behaviour of the filter that the validation shouldn't be performed if both inputs aren't inserted

2022-04-26 06:50 UTC, perfli approved these changes

2022-04-26 06:58 UTC, merged