INTYGFV-14695: Added launchId to react-frontend to handle Cerner post…
sklintyg/frontend pull request #496
Opened 2022-09-27 06:09 UTC by ChrilleSigerhed

… jump.

2022-09-27 06:44 UTC, SamuelTilly commented
@ChrilleSigerhed first PR to the React codebase? Looks good! 🥳 🎊 🎉

2022-09-27 10:46 UTC, mww-sopra-steria requested changes
A few comments to look at before merging and I'm not seeing any unit tests. Is it possible to do something here?

2022-09-27 10:46 UTC, mww-sopra-steria commented on packages/webcert/src/components/error/errorPageContent/InvalidLaunchIdError.tsx
> +export const TIMEOUT_TITLE = 'Intyget kan inte visas'
Maybe rename the constants to something else than "TIMEOUT" :-)

2022-09-27 10:46 UTC, mww-sopra-steria commented on packages/webcert/src/store/api/apiMiddleware.ts
> +    if (launchIdPresentInResponse(response) && !sessionStorage.getItem('launchId')) {
I believe this code should belong to the userMiddleware. The launchId is part of the user and is not generic logic. If the user changes this logic need to change.

2022-09-27 10:46 UTC, mww-sopra-steria commented on packages/webcert/src/store/api/apiMiddleware.ts
> +      headers: addLaunchIdIfPresent(),
Maybe rename "addLaunchIdIfPresent()" to something "getHeaders()" and then within the method add launchId if it exists?

2022-09-27 10:46 UTC, mww-sopra-steria commented on packages/webcert/src/store/api/apiMiddleware.ts
> +  if (response.data && response.data.INVALID_LAUNCHID) {
Adjust based on the changes ask for in the Webcert PR. If you change in Webcert to use errorCode and message in the response, this code is redundant and the existing code on line 91 will work out of the box.

2022-10-04 05:41 UTC, mww-sopra-steria approved these changes
Nice!

2022-10-04 05:53 UTC, merged