Feature/intygfv 14849
sklintyg/frontend pull request #523
Opened 2022-10-25 08:34 UTC by SopraErik

Support for modals when signing certificate
Modals are controlled by resource links
if resource link SIGN_CERTIFICATE_CONFIRMATION is present, the sign button will be visible and  a modal will always be displayed when the button is clicked
If resource link SIGN_CERTIFICATE **is not** present, a confirmation button will not be displayed, and the user may only cancel 
(eg. when a signed death certificate already exists)
If resource link SIGN_CERTIFICATE **is** present the user may choose to continue with signing or abort
(eg. when a deat certificate draft exists)
If no SIGN_CERTIFICATE_CONFIRMATION  exists, but SIGN_CERTIFICATE exists, the sign buttn will show, but no modal will be displayed

2022-10-27 12:45 UTC, HelenaEdblad requested changes

2022-10-27 12:45 UTC, HelenaEdblad commented on packages/webcert/src/feature/certificate/Buttons/SignAndSendButton.tsx
> +          <></>
I think you can write it like this to avoid the empty element:

```
body && (
  <div>
    <p>{body}</p>
  </div>
)
```

2022-10-27 13:05 UTC, SamuelTilly approved these changes
Some minor tweaks could be made, but looks really nice! 🥇

2022-10-31 06:56 UTC, SopraErik commented
@HelenaEdblad can you please review my changes so that I can merge the branch

2022-10-31 09:54 UTC, HelenaEdblad commented
Since Samuel approved the PR I will dismiss my review.

2022-10-31 09:55 UTC, HelenaEdblad approved these changes

2022-10-31 10:07 UTC, merged