Update cypress to version 10.10 and fix test cases
sklintyg/frontend pull request #540
Opened 2022-11-02 09:05 UTC by BjornNMT

2022-11-02 10:04 UTC, SamuelTilly approved these changes

2022-11-02 10:05 UTC, SamuelTilly commented
Awesome work 🥇

2022-11-02 13:57 UTC, SamuelTilly requested changes
After closer investigation, I think we need to address these dynamically created classes that are used in query selections. Perhaps adding `data-testid` to the "sign certificate" button is sufficient.

2022-11-02 14:43 UTC, BjornNMT commented on packages/webcert-e2e/support/FK_intyg/fk_helpers.js
> +    cy.get('.fhrpJS > .ic-button').should('be.visible');
I agree, that would be the best solution. It is also the suggested best practice in Cypress: [Selecting Elements](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements)

2022-11-03 09:24 UTC, SamuelTilly approved these changes

2022-11-03 09:49 UTC, merged