Bug/intygfv 14940 - Patient address can be editable
sklintyg/frontend pull request #547
Opened 2022-11-04 14:09 UTC by SopraErik

2022-11-04 15:19 UTC, ChrilleSigerhed commented on packages/webcert/src/feature/certificate/PatientAddress/PatientAddress.tsx
> +  const validationErrors = useSelector(getCareUnitValidationErrors(), _.isEqual)
Should this be patientValidationErrors?

2022-11-04 15:28 UTC, SopraErik commented on packages/webcert/src/feature/certificate/PatientAddress/PatientAddress.tsx
> +  const validationErrors = useSelector(getCareUnitValidationErrors(), _.isEqual)
of course. very observant! Fixed now.

2022-11-07 07:11 UTC, ChrilleSigerhed requested changes
I checked out the branch and did some checks to see how the implemented logic works. Here is a listing of my findings.

1. Unable to type in the component in a user friendly way, seems related to dispatch.
2. The field postaddress should be expandable: https://inera.atlassian.net/wiki/spaces/IT/pages/9805812/I+-+WC+Inputkomponenter+standard#6.1-Postadress
3. The asterix seems missplaced, this is same for "vardenhet" on the bottom of the page, would a fix for this make sense?

2022-11-07 09:53 UTC, SopraErik commented on packages/common/src/utils/validationUtils.ts
> +export const PATIENT_STREET_FIELD = 'grunddata.patient.postadress'
I can't seem to provoke any vissible error messages for the care unit either, maybe there aren't any?, but I've adjusted the components and client validation and inputs for patient address to be similar to care unit

2022-11-07 11:56 UTC, ChrilleSigerhed approved these changes
Nice, looks great!

2022-11-07 11:58 UTC, merged