Feature/intygfv 14887 - UeCauseOfDeath and UeCauseOfDeathList components
sklintyg/frontend pull request #553
Opened 2022-11-10 11:28 UTC by SopraErik

UeCauseOfDeath can be uset for other diseases that contributed-control as well. If label is omitted fron the config, the controlled will be dtyled as such, and the individual components will be displayed on the same row

2022-11-11 14:01 UTC, SamuelTilly requested changes

2022-11-11 14:01 UTC, SamuelTilly commented on packages/common/src/components/Inputs/Dropdown.tsx
> +        <select css={heightStyle} value={value} name={name} id={id} disabled={disabled} onChange={onChange}>
Use styled component instead of CSS properties.

2022-11-11 15:07 UTC, SopraErik commented on packages/common/src/utils/faker/fakeCertificateData.ts
> +              { id: 'PLOTSLIG', label: 'Plötslig' },
So probably AKUT I guess, this needs to be synced with backend @mww-sopra-steria @ChrilleSigerhed

2022-11-14 06:53 UTC, SopraErik commented on packages/common/src/components/Inputs/Dropdown.tsx
> +    : css``
yes ,definitely, seems to be due to some application specific modifications to inera css in index.css

2022-11-14 07:41 UTC, SopraErik commented on packages/common/src/components/Inputs/Dropdown.tsx
> +    : css``
I have created a bug now: 
[https://inera.atlassian.net/browse/INTYGFV-14970](https://inera.atlassian.net/browse/INTYGFV-14970)

2022-11-16 09:55 UTC, SopraErik commented
Significant changes made to this now since the PR originally was created, as the data model changed. This PR now also handles additional diseases and the ability to add more rows. @ChrilleSigerhed , @mww-sopra-steria , @SamuelTilly , @HelenaEdblad @UlrikaSopra , please review it again

2022-11-17 06:35 UTC, SopraErik commented
Converting this into draft, as there are still some issues, such as deletion of rows, that needs to be solved

2022-11-22 14:05 UTC, SopraErik commented
Thanks @SamuelTilly , nice work!

2022-11-29 13:36 UTC, merged