Feature/INTYGFV-14897: Button for showing related certificate in DB
sklintyg/frontend pull request #569
Opened 2022-11-23 10:56 UTC by UlrikaSopra

2022-11-25 10:00 UTC, HelenaEdblad requested changes
Nice! I tested the code and I noticed that the tooltip stays visible even after the redirect. See screenshot: 
![image](https://user-images.githubusercontent.com/85883491/203955240-83d54188-2c82-4c68-b0b7-65dcdef0e640.png)

2022-11-25 10:00 UTC, HelenaEdblad commented on packages/webcert/src/feature/certificate/Buttons/Test/ShowRelatedCertificateButton.test.tsx
> +        certificateId={certificateMetadata.id}
Will this have an id since the certificateMetadata is an empty object?

2022-11-29 07:43 UTC, SamuelTilly approved these changes
Very nice! 👍

2022-11-29 08:07 UTC, HelenaEdblad approved these changes

2022-11-29 08:10 UTC, merged