INTYGFV-14970: Adjust heights on input fields
sklintyg/frontend pull request #588
Opened 2022-12-06 16:32 UTC by HelenaEdblad

2022-12-06 16:50 UTC, HelenaEdblad commented
We decided that the input fields TextInput, Dropdown and DatePicker should be the same height as the TextInput, which is 49.29px (which is 2.956rem).

2022-12-07 11:04 UTC, SopraErik requested changes

2022-12-07 11:04 UTC, SopraErik commented on packages/webcert/src/feature/certificate/Inputs/UeCauseOfDeath/UeCauseOfDeathList.tsx
> +                        height="2.956rem">
I think this wil probably not be the only case when we will need an in-line button.
I would prefer not to set the height here, but rather maybe a separate control for inline button.

2022-12-08 15:31 UTC, HelenaEdblad commented
Changed the height to 48px (3rem) because that makes more sence..

2022-12-09 10:48 UTC, SopraErik approved these changes
Great, looking good!

2022-12-09 11:55 UTC, merged