INTYGFV-15240: Added shadow when focusing on input with error
sklintyg/frontend pull request #666
Opened 2023-02-01 10:09 UTC by mhornfeldt

2023-02-01 11:09 UTC, SamuelTilly requested changes
Looks good for TextInput, but we should probably fix TextArea as well.

![image](https://user-images.githubusercontent.com/28404/216026558-2017d247-92d0-4350-a57d-bc7ff6205c04.png)

Missing shadow and background changes when gaining focus.

2023-02-01 11:19 UTC, SamuelTilly commented
I added a bunch of storiebooks for the shared components to make this a bit easier.

2023-02-01 13:55 UTC, SopraErik requested changes
Text area gets pink background on focus even if there are no validation errors
![image](https://user-images.githubusercontent.com/92843575/216062355-4096e2ce-8e7c-4c98-abd4-8a7b83feaaa3.png)

2023-02-02 08:21 UTC, SamuelTilly approved these changes

2023-02-02 08:21 UTC, SamuelTilly approved these changes

2023-02-02 08:25 UTC, SopraErik approved these changes

2023-02-02 10:26 UTC, merged