Bug/INTYGFV-15000: Disallow input of numbers that start with 0 and more characters
sklintyg/frontend pull request #674
Opened 2023-02-06 10:17 UTC by UlrikaSopra

2023-02-06 10:26 UTC, SopraErik requested changes
If I start to type in a number starting with 0, no further entry is possible.
Also, I can enter -01, but gets an error

![image](https://user-images.githubusercontent.com/92843575/216947652-3326bbcb-bdd8-4c04-b5db-0d2f34d76327.png)

![image](https://user-images.githubusercontent.com/92843575/216947800-f406451c-f298-4371-8a4e-d1ec6d15d583.png)

2023-02-07 09:17 UTC, SopraErik commented on packages/webcert/src/feature/certificate/UnifiedEdit/UeInteger/UeInteger.tsx
> +  const [number, setNumber] = useState(questionValue.value?.toString() ?? undefined)
Maybe a better idea would be to have the local state numeric rather than string?

2023-02-07 10:10 UTC, SopraErik approved these changes
Now it seems to work as intended :)

2023-02-07 10:11 UTC, UlrikaSopra commented
> Now it seems to work as intended :)

Finally! :D

2023-02-07 10:25 UTC, merged