INTYGFV-15395: Added SRS panel
sklintyg/frontend pull request #756
Opened 2023-03-06 12:35 UTC by mhornfeldt

2023-03-07 13:17 UTC, SamuelTilly requested changes
Very nice work! Left some minor suggestions

2023-03-07 13:17 UTC, SamuelTilly commented on packages/webcert/src/feature/certificate/CertificateSidePanel/CertificateSidePanel.tsx
> +        return <FMBPanel></FMBPanel>
Very minor `<FMBPanel />`

2023-03-07 13:17 UTC, SamuelTilly commented on packages/webcert/src/feature/certificate/CertificateSidePanel/CertificateSidePanel.tsx
> +    tabsArray.push(getTab('Om intyget', 'Läs om intyget'))
Good refactoring here, but I think we can take it a bit further.

We can create a list with resource links for tabs:
```typescript
const resourceLinksForTabs = [
  ResourceLinkType.SRS,
  ResourceLinkType.FMB,
  ResourceLinkType.QUESTIONS,
  ResourceLinkType.QUESTIONS_NOT_AVAILABLE,
]
const availableTabs = resourceLinks.filter(({ type }) => resourceLinksForTabs.includes(type))
```
Then we can remove the `getTabs` function and simply do:

```typescript
return (
  <Tabs
    selectedTabIndex={selectedTabIndex}
    setSelectedTabIndex={handleTabChange}
    tabs={[
      ...availableTabs.map(({ type, name, description }) => getTab(name, description, getIcon(type))),
      getTab('Om intyget', 'Läs om intyget'),
    ]}
    tabsContent={[...availableTabs.map(({ type }) => getPanel(type)), <AboutCertificatePanel key={'about'} />]}
  />
)
```

2023-03-08 07:38 UTC, mhornfeldt commented on packages/webcert/src/components/srs/SRSPanel.tsx
> +  }
I think it's better with the function since the condition is used in several places

2023-03-08 11:47 UTC, SamuelTilly approved these changes

2023-03-08 13:45 UTC, merged