INTYGFV-15374: Added statement for Show personal data in patient view
sklintyg/frontend pull request #839
Opened 2023-04-19 10:51 UTC by UlrikaSopra

2023-04-19 12:29 UTC, SamuelTilly requested changes
Very nice, this could use some tests to make sure we display information correctly.

2023-04-19 12:30 UTC, UlrikaSopra commented
> Very nice, this could use some tests to make sure we display information correctly.

working on it :)

2023-04-27 06:19 UTC, SamuelTilly requested changes
We can make it a bit simpler to use faker functions. In addition to the things I list, we need to update the `deepmerge` function in `packages\fake\src\index.ts` so that it doesn't merge arrays.

```typescript
const customDeepmerge = deepmergeCustom<{
  DeepMergeArraysURI: DeepMergeLeafURI
}>({
  mergeArrays: false,
})

export function fakerFromSchema<T extends ZodTypeAny>(schema: T, options?: GenerateMockOptions) {
  return (data?: DeepPartial<z.infer<T>>) => customDeepmerge(generateMock(schema, { stringMap, faker, ...options }), data ?? {})
}
```

2023-04-27 06:19 UTC, SamuelTilly commented on apps/rehabstod/src/pages/Patient/components/PatientHeader.test.tsx
> +  })
We can make this a bit simpler, but i noticed an issue with how our faker package handles mergers.

```tsx
function renderPatientHeader(showPersonalInformation: boolean) {
  const patient = fakePatient({
    sjukfallList: [
      {
        intyg: [
          {
            start: '2023-04-25',
            slut: '2023-05-01',
            patient: {
              alder: 30,
              kon: 'Kvinna',
              namn: 'Olle',
              id: '123',
            },
          },
        ],
      },
    ],
  })
  store.dispatch(updateShowPersonalInformation(showPersonalInformation))
  renderWithRouter(<PatientHeader patient={patient} />)
}
```

2023-04-27 06:19 UTC, SamuelTilly commented on apps/rehabstod/src/utils/fake/fakePatient.ts
> +} as Omit<GenerateMockOptions, 'sjfMetaData'>)
We can use `fakerFromSchemaFactory` to wrap our faker in another layer, this avoids the typescript issue.

```typescript
export const fakePatient = fakerFromSchemaFactory(patientSchema, {
  sjukfallList: Array.from({ length: faker.datatype.number({ min: 1, max: 5 }) }, fakePatientSjukfall),
  srsError: faker.datatype.boolean(),
  kompletteringInfoError: faker.datatype.boolean(),
})
```

2023-04-27 08:47 UTC, UlrikaSopra commented
> We can make it a bit simpler to use faker functions. In addition to the things I list, we need to update the `deepmerge` function in `packages\fake\src\index.ts` so that it doesn't merge arrays.
> 
> ```ts
> const customDeepmerge = deepmergeCustom<{
>   DeepMergeArraysURI: DeepMergeLeafURI
> }>({
>   mergeArrays: false,
> })
> 
> export function fakerFromSchema<T extends ZodTypeAny>(schema: T, options?: GenerateMockOptions) {
>   return (data?: DeepPartial<z.infer<T>>) => customDeepmerge(generateMock(schema, { stringMap, faker, ...options }), data ?? {})
> }
> ```

2023-04-27 09:21 UTC, SamuelTilly approved these changes

2023-04-27 12:46 UTC, merged