INTYGFV-15367: Anpassa kolumner
sklintyg/frontend pull request #863
Opened 2023-04-27 05:23 UTC by SamuelTilly

2023-04-28 10:46 UTC, UlrikaSopra reviewed
Great job!! 👯  just a small thing, if you have chosen not to show personal data, the social security number and name etc. are still in the list (= Maybe a question for Rebecka.

![image](https://user-images.githubusercontent.com/79509664/235127024-8e0e95d6-1116-40a2-b120-200e35561413.png)

2023-05-04 13:32 UTC, mhornfeldt commented on apps/rehabstod/src/pages/CurrentSickLeaves/CurrentSickLeaves.tsx
> +      <Table sortColumn={SjukfallColumn.Startdatum}>
We should use the term SickLeave instead of Sjukfall

2023-05-04 13:35 UTC, mhornfeldt requested changes
Change Sjukfall to SickLeave

2023-05-08 07:11 UTC, SamuelTilly commented
> Change Sjukfall to SickLeave

Good call, has been changed to SickLeave

2023-05-08 11:15 UTC, mhornfeldt approved these changes

2023-05-08 11:37 UTC, merged