INTYGFV-15612: DatePicker, Calendar & Slutdatum
sklintyg/frontend pull request #912
Opened 2023-05-16 13:35 UTC by SamuelTilly

2023-06-14 07:03 UTC, ChrilleSigerhed requested changes
Awsome, you really done a great job with this component! Very impressive.

The component works great, the only functional flaw that I could find is that when clicking the reset filter-button the values does not reset.

Code-wise I suggest we add some tests for the classes that is missing tests. If you feel like it's redundant for some of the components I can understand that. 

For me the tests also can work as documentation of the components, so I think it could make the components easier to understand aswell!

Again, great work!

2023-06-14 07:03 UTC, ChrilleSigerhed commented on apps/rehabstod/src/utils/TestProvider.tsx
> +// createMemoryRouter()
Remove this comment?

2023-06-16 08:14 UTC, SamuelTilly commented on apps/rehabstod/src/components/Popover/Popover.tsx
> +export function Popover({ children, ...props }: PopoverProps & { children: ReactNode }) {
Not sure what tests I could add here, most of the logic will only affect styling and that is not something we test for usually. Elements will for example always be shown, only hidden with positioning and height styling.

2023-06-16 08:26 UTC, ChrilleSigerhed commented on apps/rehabstod/src/components/Popover/Popover.tsx
> +export function Popover({ children, ...props }: PopoverProps & { children: ReactNode }) {
Makes sense.

2023-06-16 09:04 UTC, ChrilleSigerhed approved these changes
Awsome, really impressive! Remember to fix the userEvent setup before merging.

2023-06-16 09:24 UTC, merged