Simplify CurrentSickLeaves table rows
sklintyg/frontend pull request #972
Opened 2023-06-14 13:30 UTC by SamuelTilly

2023-06-16 08:42 UTC, mhornfeldt requested changes

2023-06-16 12:49 UTC, SamuelTilly commented on apps/rehabstod/src/pages/CurrentSickLeaves/utils/getSickLeavesColumnData.ts
> +      return getUnansweredCommunicationsFormat(sickLeave.obesvaradeKompl, sickLeave.unansweredOther)
Would it not be more correct, tho? We would sort on the same string we present.

2023-06-20 12:12 UTC, mhornfeldt commented on apps/rehabstod/src/pages/CurrentSickLeaves/utils/getSickLeavesColumnData.ts
> +      return getUnansweredCommunicationsFormat(sickLeave.obesvaradeKompl, sickLeave.unansweredOther)
I don't think that's how the sorting in the original application works

2023-06-21 05:41 UTC, SamuelTilly commented on apps/rehabstod/src/pages/CurrentSickLeaves/utils/getSickLeavesColumnData.ts
> +      return getUnansweredCommunicationsFormat(sickLeave.obesvaradeKompl, sickLeave.unansweredOther)
I think you are right. Reversed the change to "Ärenden"

2023-07-04 06:54 UTC, merged